@startuml
title Client/IoC Server/Analyzer Protocol
activate Client
activate IoCServer
activate Analyzer
alt successful case
    note right of Analyzer:Submit malware for analysis
    Analyzer-->IoCServer:send(analysis_results)
else
    group failure case 4
    Analyzer-->IoCServer:(False,'Failing to submit malware')
    end
else
    note left of IoCServer:Generate MAEC XML
    IoCServer-->Client:(maec_hash,client_id,malware_hash,length,time,subject_name)
    Client->IoCServer:('ready','Ready to receive analysis results')
    IoCServer-->Client:send(maec.xml)
    Client->IoCServer:(True,'Results delivered successfully')
end
@enduml